apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
#  annotations:
#    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Image","apiVersion":"kpack.io/v1alpha1","metadata":{"name":"sqlrunner","namespace":"default","creationTimestamp":null},"spec":{"tag":"registry.planet10.lab/apps/sqlrunner","builder":{"kind":"ClusterBuilder","name":"default"},"serviceAccount":"default","source":{"git":{"url":"https://github.com/sdeeg-pivotal/sqlrunner.git","revision":"main"}},"build":{"resources":{}}},"status":{}}'
#  creationTimestamp: null
  name: sqlrunner
  namespace: builds
spec:
  tag: registry.planet10.lab/apps/sqlrunner
  build:
    resources: {}
  builder:
    kind: ClusterBuilder
    name: base
  serviceAccount: kpack-sa
  source:
    git:
      revision: master
      url: https://github.com/sdeeg-pivotal/sqlrunner.git
status: {}
