apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Image","apiVersion":"kpack.io/v1alpha1","metadata":{"name":"sqlrunner","namespace":"default","creationTimestamp":null},"spec":{"tag":"registry.planet10.lab/apps/sqlrunner","builder":{"kind":"ClusterBuilder","name":"default"},"serviceAccount":"default","source":{"git":{"url":"https://github.com/sdeeg-pivotal/sqlrunner.git","revision":"main"}},"build":{"resources":{}}},"status":{}}'
  creationTimestamp: null
  name: sqlrunner
  namespace: default
spec:
  build:
    resources: {}
  builder:
    kind: ClusterBuilder
    name: default
  serviceAccount: default
  source:
    git:
      revision: main
      url: https://github.com/sdeeg-pivotal/sqlrunner.git
  tag: registry.planet10.lab/apps/sqlrunner
status: {}
