apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sqlrunner-np
  name: sqlrunner-np
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: sqlrunner
  type: NodePort
status:
  loadBalancer: {}
