apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sqlrunner
  name: sqlrunner-deployment
  labels:
    app: sqlrunner
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sqlrunner
  template:
    metadata:
      labels:
        app: sqlrunner
    spec:
      containers:
      - name: sqlrunner
#        image: registry.planet10.lab/apps/sqlrunner:latest
#        image: registry.planet10.lab/apps/sqlrunner@sha256:xxx
        image: registry.planet10.lab/apps/sqlrunner:b3.20210729.232859
      imagePullSecrets:
      - name: harbor-credentials
