apiVersion: v1
kind: Namespace
metadata:
  name: sqlrunner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sqlrunner
  labels:
    app: sqlrunner
  name: sqlrunner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlrunner
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sqlrunner
    spec:
      containers:
      - image: registry.planet10.lab/util/sqlrunner
        name: sqlrunner
        resources: { }
      imagePullSecrets:
      - name: harbor-credentials
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: sqlrunner
  labels:
    app: sqlrunner-np
  name: sqlrunner-np
spec:
  ports:
    - name: sqlrunner-svc-ports
      port: 80
      targetPort: 8080
      nodePort: 32438
      protocol: TCP
  selector:
    app: sqlrunner
  type: NodePort
status:
  loadBalancer: {}
